### ISSUE TITLE
StarvationViolacein_Infinite_07272015_WJB.csv, no infinite CFU count

### ISSUE THREAD

**Issue by wrshoemaker** [LennonLab/JanthinoViol#10]
There's a violacein extraction file for the "infinite" lines (cultures started since @jaredbrewer 's first week), but there's no file for CFU counts. Does that exist?

**Comment by jaredbrewer** [comment]
I just did that today, to get the longest time possible. The CFU counts will come whenever the plates grow (probably by Wednesday). 
- Jared

**Comment by wrshoemaker** [comment]
Awesome!
